collect_data: true
create_dataset: true
train_model: true
train_model_onestep: true

experiment:
  traj_len: 100
  num_traj: 3
  split: .8

nn:
  ensemble: false
  training:
    hid_width: 250
    hid_depth: 2
    E: 5
    plot_loss: false
  optimizer:
    epochs: 33
    batch: 18
    name: Adam
    split: .8
    lr: .0025
