model:
  str: c
  prob: false
  ensemble: false
  traj: false
  delta: false
  training:
    hid_width: 250
    hid_depth: 2
    E: 1
    # Note: these do nothing for non trajectory based models
    train_target: true
    control_params: true
    # the state indices to worry about for model
    state_indices: [0,1,2,3,4]
  optimizer:
    epochs: 16
    batch: 32
    name: Adam
    split: .8
    lr: .00005
    max_size: 0
  preprocess:
    state:
      class: sklearn.preprocessing.StandardScaler
      #Choose between standard scaler and min max scaler
      #class: sklearn.preprocessing.MinMaxScaler
        #params:
          #feature_range: [-1.,1.]"""
    action:
      class: sklearn.preprocessing.StandardScaler
    output:
      class: sklearn.preprocessing.StandardScaler
  plotting:
    label: Custom
    color: '#8d67a6'
    color_plotly: rgb(141,103,166)
    marker: *
    marker_plotly: star