model:
  str: d
  prob: false
  ensemble: false
  traj: false
  delta: true
  training:
    hid_width: 250
    hid_depth: 2
    E: 1
    # Note: these do nothing for non trajectory based models
    train_target: true
    control_params: true
  optimizer:
    epochs: 25
    batch: 32
    name: Adam
    split: .8
    lr: .00008
    max_size: 0
  preprocess:
    state:
      class: sklearn.preprocessing.StandardScaler
      #Choose between standard scaler and min max scaler
      #class: sklearn.preprocessing.MinMaxScaler
        #params:
          #feature_range: [-1.,1.]"""
    action:
      class: sklearn.preprocessing.StandardScaler
    output:
      class: sklearn.preprocessing.StandardScaler
  plotting:
    label: One Step Deterministic
    color: '#0033ff'
    color_plotly: rgb(0,0,128)
    marker: o
    marker_plotly: circle-open-dot

