model:
  str: d
  prob: false
  ensemble: false
  traj: false
  training:
    hid_width: 250
    hid_depth: 2
    E: 1
  optimizer:
    epochs: 3
    batch: 128
    name: Adam
    split: .8
    lr: .003
  preprocess:
    state:
      class: sklearn.preprocessing.StandardScaler
      #Choose between standard scaler and min max scaler
      """class: sklearn.preprocessing.MinMaxScaler
            params:
              feature_range: [-1.,1.]"""
    action:
      class: sklearn.preprocessing.StandardScaler
    output:
      class: sklearn.preprocessing.StandardScaler
