model:
  str: d_less_states
  prob: false
  ensemble: false
  traj: false
  delta: true
  training:
    hid_width: 250
    hid_depth: 2
    E: 1
    # Note: these do nothing for non trajectory based models
    train_target: true
    control_params: true
    # the state indices to worry about for model
    state_indices: [0,1,2,3,4,5,6,7,8,9,13,14,15,16,17]
    state_indices_lorenz: [0,1,2]
  optimizer:
    epochs: 40
    batch: 32
    name: Adam
    split: .8
    lr: .00002
    max_size: 0
  preprocess:
    state:
      class: sklearn.preprocessing.StandardScaler
      #Choose between standard scaler and min max scaler
      #class: sklearn.preprocessing.MinMaxScaler
        #params:
          #feature_range: [-1.,1.]"""
    action:
      class: sklearn.preprocessing.StandardScaler
    output:
      class: sklearn.preprocessing.StandardScaler
  plotting:
    label: One Step Deterministic with less States
    color: '#34eb98'
    color_plotly: rgb(52,235,152)
    marker: o
    marker_plotly: circle-open-dot
