model:
  str: d_state
  prob: false
  ensemble: false
  traj: false
  delta: false
  gp: false
  lstm: false
  training:
    hid_width: 250
    hid_depth: 2
    E: 1
    # Note: these do nothing for non trajectory based models
    train_target: true
    control_params: true
    # the state indices to worry about for model
#    state_indices: [0,1,2,3,4,5,6,7,8,9,13,14,15,16,17]
    state_indices_lorenz: [0,1,2]
  optimizer:
    epochs: 20
    batch: 32 #32
    name: Adam
    split: .8
    lr: .0001
    regularization: 0 #0.003
    max_size: 0
  plotting:
    label: One Step Deterministic State Based
    color: '#8d67a6'
    color_plotly: rgb(141,103,166)
    marker: '*'
    marker_plotly: star
