model:
  str: gp
  prob: false
  ensemble: false
  traj: false
  delta: true
  gp: true
  training:
    hid_width: 250
    hid_depth: 2
    E: 1
    # Note: these do nothing for non trajectory based models
    train_target: true
    control_params: true
    filter_rate: 0.0
    num_traj: 50
  optimizer:
    epochs: 25
    batch: 32
    name: Adam
    split: .8
    lr: .0001
    regularization: 0.003
    max_size: 50
  plotting:
    label: Gaussian Process
    color: '#0033ff' #todo
    color_plotly: rgb(0,0,200) #todo
    marker: o #todo
    marker_plotly: circle-open-dot #todo
