model:
  str: p
  prob: true
  ensemble: false
  traj: false
  training:
    hid_width: 250
    hid_depth: 2
    E: 1
  optimizer:
    epochs: 18
    batch: 32
    name: Adam
    split: .8
    lr: .0001