model:
  str: p
  prob: true
  ensemble: false
  traj: false
  delta: true
  gp: false
  training:
    hid_width: 250
    hid_depth: 2
    E: 1
    # Note: these do nothing for non trajectory based models
    train_target: true
    control_params: true
    filter_rate: 0.0
    t_range: 500
    num_traj: 50
  optimizer:
    epochs: 25
    batch: 64
    name: Adam
    split: .8
    lr: .000025
    regularization: 0
    max_size: 0
#  preprocess:
#    state:
#      class: sklearn.preprocessing.StandardScaler # sklearn.preprocessing.MinMaxScaler
#    #  params:
#    #    feature_range: [-1.,1.]
#      #Choose between standard scaler and min max scaler
#      #class: sklearn.preprocessing.MinMaxScaler
#        #params:
#          #feature_range: [-1.,1.]
#    action:
#      class: sklearn.preprocessing.MinMaxScaler
#      params:
#        feature_range: [-1.,1.]
#    output:
#      class: sklearn.preprocessing.StandardScaler
  plotting:
    label: One Step Probabilistic
    color: '#00c414'
    color_plotly: rgb(0,128,0)
    marker: D
    marker_plotly: x-open-dot
