model:
  str: pe
  prob: true
  ensemble: true
  traj: false
  delta: true
  gp: false
  training:
    hid_width: 250
    hid_depth: 2
    E: 5
    # Note: these do nothing for non trajectory based models
    train_target: true
    control_params: true
    filter_rate: 0.0
    num_traj: 50
    state_indices_lorenz: [0,1,2]
  optimizer:
    epochs: 25
    batch: 64
    name: Adam
    split: .8
    lr: .000025
    regularization: 0.001
    max_size: 0
#  preprocess:
#    state:
#      class: sklearn.preprocessing.StandardScaler
#      #Choose between standard scaler and min max scaler
#      #class: sklearn.preprocessing.MinMaxScaler
#        #params:
#          #feature_range: [-1.,1.]
#    action:
#      class: sklearn.preprocessing.StandardScaler
#    output:
#      class: sklearn.preprocessing.StandardScaler
  plotting:
    label: One Step Probabilistic Ensemble
    color: '#52b536'
    color_plotly: rgb(20,128,20)
    marker: D
    marker_plotly: hourglass-open
