model:
  str: t
  prob: false
  ensemble: false
  traj: true
  delta: false
  gp: false
  training:
    hid_width: 500 # 250
    hid_depth: 3 # 2
    E: 1
    # Note: these do nothing for non trajectory based models
    train_target: true
    control_params: true
    filter_rate: 0.95
#    t_range: 500
    num_traj: 50
  optimizer:
    epochs: 22
    batch: 32
    name: Adam
    split: .8
    lr: .0008 # 4
    regularization: 0
    max_size: 100000
  preprocess:
    state:
      class: sklearn.preprocessing.MinMaxScaler
      params:
        feature_range: [-1.,1.]
    index:
      class: sklearn.preprocessing.MinMaxScaler
      params:
        feature_range: [-1.,1.]
    param:
      class: sklearn.preprocessing.MinMaxScaler
      params:
        feature_range: [-1.,1.]
    output:
      class: sklearn.preprocessing.StandardScaler
  plotting:
    label: Trajectory Based Deterministic
    color: '#ff0000'
    color_plotly: rgb(200,0,0)
    marker: s
    marker_plotly: cross-open-dot
