model:
  str: t_less_states_no_pid
  prob: false
  ensemble: false
  traj: true
  delta: false
  training:
    hid_width: 250
    hid_depth: 2
    E: 1
    # Note: these do nothing for non trajectory based models
    train_target: true
    control_params: false
    # the state indices to worry about for model
    state_indices: [0,1,2,3,4]
    state_indices_lorenz: [0,1,2]
  optimizer:
    epochs: 20
    batch: 32
    name: Adam
    split: .8
    lr: .00002
    max_size: 50000
  preprocess:
    state:
      class: sklearn.preprocessing.StandardScaler
    index:
      class: sklearn.preprocessing.MinMaxScaler
      params:
        feature_range: [-1.,1.]
    param:
      class: sklearn.preprocessing.MinMaxScaler
      params:
        feature_range: [-1.,1.]
    output:
      class: sklearn.preprocessing.StandardScaler
  plotting:
    label: TD with less States, no PID Params
    color: '#00dc79'
    color_plotly: rgb(0,220,121)
    marker: s
    marker_plotly: cross-open-dot
