model:
  str: t_no_pid
  prob: false
  ensemble: false
  traj: true
  delta: false
  training:
    hid_width: 250
    hid_depth: 2
    E: 1
    # Note: these do nothing for non trajectory based models
    train_target: true
    control_params: false
  optimizer:
    epochs: 20
    batch: 32
    name: Adam
    split: .8
    lr: .00002
    max_size: 50000
  preprocess:
    state:
      class: sklearn.preprocessing.StandardScaler
    index:
      class: sklearn.preprocessing.MinMaxScaler
      params:
        feature_range: [-1.,1.]
    param:
      class: sklearn.preprocessing.MinMaxScaler
      params:
        feature_range: [-1.,1.]
    output:
      class: sklearn.preprocessing.StandardScaler
  plotting:
    label: TD without PID parameters
    color: '#ff1100'
    color_plotly: rgb(200,0,0)
    marker: s
    marker_plotly: cross-open-dot
