model:
  str: t_no_target
  prob: false
  ensemble: false
  traj: true
  delta: false
  training:
    hid_width: 250
    hid_depth: 2
    E: 1
    # Note: these do nothing for non trajectory based models
    train_target: false
    control_params: true
    # the state indices to worry about for model
    state_indices: [0,1,2,3,4]
  optimizer:
    epochs: 20
    batch: 32
    name: Adam
    split: .8
    lr: .00002
    max_size: 50000
  preprocess:
    state:
      class: sklearn.preprocessing.StandardScaler
    index:
      class: sklearn.preprocessing.MinMaxScaler
      params:
        feature_range: [-1.,1.]
    param:
      class: sklearn.preprocessing.MinMaxScaler
      params:
        feature_range: [-1.,1.]
    output:
      class: sklearn.preprocessing.StandardScaler
  plotting:
    label: TD without Target
    color: '#fa0c9f'
    color_plotly: rgb(250,12,159)
    marker: s
    marker_plotly: cross-open-dot
