model:
  str: t_range_50
  prob: false
  ensemble: false
  traj: true
  delta: false
  training:
    hid_width: 250
    hid_depth: 2
    E: 1
    # Note: these do nothing for non trajectory based models
    train_target: true
    control_params: true
    # the state indices to worry about for model
    state_indices: [0,1,2,3,4,5,6,7,8,9,13,14,15,16,17]
    filter_rate: 0.0
    t_range: 50
  optimizer:
    epochs: 50
    batch: 32
    name: Adam
    split: .8
    lr: .0004
    max_size: 50000
  preprocess:
    state:
      class: sklearn.preprocessing.StandardScaler
    index:
      class: sklearn.preprocessing.MinMaxScaler
      params:
        feature_range: [-1.,1.]
    param:
      class: sklearn.preprocessing.MinMaxScaler
      params:
        feature_range: [-1.,1.]
    output:
      class: sklearn.preprocessing.StandardScaler
  plotting:
    label: Trajectory Based Deterministic, length 50
    color: '#8f32a8'
    color_plotly: rgb(143,50,168)
    marker: s
    marker_plotly: cross-open-dot
