model:
  str: te
  prob: false
  ensemble: true
  traj: true
  delta: false
  gp: false
  lstm: false
  training:
    hid_width: 250
    hid_depth: 2
    E: 5
    # Note: these do nothing for non trajectory based models
    train_target: true
    control_params: true
    # the state indices to worry about for model
#    state_indices: [0,1,2,3,4,5,6,7,8,9,13,14,15,16,17]
    filter_rate: 0.95
    t_range: 500
    num_traj: 50
    state_indices_lorenz: [0,1,2]
  optimizer:
    epochs: 30
    batch: 64
    name: Adam
    split: .8
    lr: .0008
    regularization: 0
    max_size: 100000
#  preprocess:
#    state:
#      class: sklearn.preprocessing.StandardScaler
#        #Choose between standard scaler and min max scaler
#        #class: sklearn.preprocessing.MinMaxScaler
#      #params:
#      #feature_range: [-1.,1.]
#    index:
#      class: sklearn.preprocessing.MinMaxScaler
#      params:
#        feature_range: [-1.,1.]
#    param:
#      class: sklearn.preprocessing.MinMaxScaler
#      params:
#        feature_range: [-1.,1.]
#    output:
#      class: sklearn.preprocessing.StandardScaler
  plotting:
    label: Trajectory Based Deterministic Ensemble
    color: '#b53636'
    color_plotly: rgb(180,20,20)
    marker: s
    marker_plotly: y-down-open
