model:
  str: tp_1
  prob: true
  ensemble: false
  traj: true
  delta: false
  training:
    hid_width: 1500
    hid_depth: 3
    E: 1
    # Note: these do nothing for non trajectory based models
    train_target: true
    control_params: true
    filter_rate: 0.95
    t_range: 500
    num_traj: 50
  optimizer:
    epochs: 30
    batch: 256 #32
    name: Adam
    split: .8
    lr: .0008 # 5
    regularization: 0
    max_size: 100000
  preprocess:
    state:
      class: sklearn.preprocessing.StandardScaler
        #Choose between standard scaler and min max scaler
        #class: sklearn.preprocessing.MinMaxScaler
      #params:
      #feature_range: [-1.,1.]
    index:
      class: sklearn.preprocessing.MinMaxScaler
      params:
        feature_range: [-1.,1.]
    param:
      class: sklearn.preprocessing.MinMaxScaler
      params:
        feature_range: [-1.,1.]
    output:
      class: sklearn.preprocessing.StandardScaler
  plotting:
    label: Trajectory Based Probabilistic
    color: '#dcdc00'
    color_plotly: rgb(200,200,0)
    marker: p
    marker_plotly: triangle-up-open-dot
