model:
  str: tp
  prob: true
  ensemble: false
  traj: true
  delta: false
  training:
    hid_width: 250
    hid_depth: 2
    E: 1
    # Note: these do nothing for non trajectory based models
    train_target: true
    control_params: true
    # the state indices to worry about for model
    state_indices: [0,1,2,3,4,5,6,7,8,9,13,14,15,16,17]
    filter_rate: 0.95
    t_range: 500
    num_traj: 50
    state_indices_lorenz: [0,1,2]
  optimizer:
    epochs: 50
    batch: 32
    name: Adam
    split: .8
    lr: .0005
    regularization: 0
    max_size: 50000
  preprocess:
    state:
      class: sklearn.preprocessing.StandardScaler
        #Choose between standard scaler and min max scaler
        #class: sklearn.preprocessing.MinMaxScaler
      #params:
      #feature_range: [-1.,1.]
    index:
      class: sklearn.preprocessing.MinMaxScaler
      params:
        feature_range: [-1.,1.]
    param:
      class: sklearn.preprocessing.MinMaxScaler
      params:
        feature_range: [-1.,1.]
    output:
      class: sklearn.preprocessing.StandardScaler
  plotting:
    label: Trajectory Based Probabilistic
    color: '#dcdc00'
    color_plotly: rgb(200,200,0)
    marker: p
    marker_plotly: triangle-up-open-dot
