model:
  str: tpe
  prob: true
  ensemble: true
  traj: true
  delta: false
  training:
    hid_width: 250
    hid_depth: 2
    E: 5
  optimizer:
    epochs: 20
    batch: 32
    name: Adam
    split: .8
    lr: .00002
    max_size: 50000
  preprocess:
    state:
      class: sklearn.preprocessing.StandardScaler
        #Choose between standard scaler and min max scaler
        #class: sklearn.preprocessing.MinMaxScaler
      #params:
      #feature_range: [-1.,1.]
    index:
      class: sklearn.preprocessing.MinMaxScaler
      params:
        feature_range: [-1.,1.]
    param:
      class: sklearn.preprocessing.MinMaxScaler
      params:
        feature_range: [-1.,1.]
    output:
      class: sklearn.preprocessing.StandardScaler