collect_data: true
create_dataset: true
train_model: true
train_model_onestep: true

experiment_one_model:
  traj_len: 600
  traj_len_test: 800
  num_traj: 10
  split: .8
  P: false
  D: false

experiment_efficiency:
  traj_len: 30
  traj_len_test: 200
  num_traj: 10

nn:
  ensemble:
    use: false
    num_nets: 10
  training:
    hid_width: 250
    hid_depth: 2
    E: 5
    plot_loss: true
    plot_loss_epoch: true
  optimizer:
    epochs: 1
    batch: 128
    name: Adam
    split: .8
    lr: .003
