collect_data: true

experiment:
  traj_len: 1000
  traj_len_test: 1000
  num_traj: 50
  num_traj_test: 5
  split: .8
  P: false
  D: false
  models:
    single:
      train_traj: true
      train_det: true
      train_prob: false
      train_prob_traj: false
    ensemble:
      train_traj: true
      train_det: true
      train_prob: false
      train_prob_traj: false

experiment_efficiency:
  traj_len: 30
  traj_len_test: 200
  num_traj: 10

nn:
  ensemble:
    n: 10
  trajectory_based:
    training:
      hid_width: 250
      hid_depth: 2
      E: 5
    optimizer:
      epochs: 1
      batch: 128
      name: Adam
      split: .8
      lr: .01
  trajectory_based_prob:
    training:
      hid_width: 250
      hid_depth: 2
      E: 5
    optimizer:
      epochs: 1
      batch: 128
      name: Adam
      split: .8
      lr: .003
  one_step_det:
    training:
      hid_width: 250
      hid_depth: 2
      E: 5
    optimizer:
      epochs: 3
      batch: 128
      name: Adam
      split: .8
      lr: .003
  one_step_prob:
    training:
      hid_width: 250
      hid_depth: 2
      E: 5
    optimizer:
      epochs: 10
      batch: 128
      name: Adam
      split: .8
      lr: .001
