collect_data: true
train_traj: true
train_det: true
train_prob: true
train_prob_traj: true
train_traj_ens: false
train_det_ens: false
train_prob_ens: false
train_prob_traj_ens: false



experiment:
  traj_len: 600
  traj_len_test: 800
  num_traj: 10
  split: .8
  P: false
  D: false

experiment_efficiency:
  traj_len: 30
  traj_len_test: 200
  num_traj: 10

nn:
  ensemble:
    n: 10
  trajectory_based:
    training:
      hid_width: 250
      hid_depth: 2
      E: 5
    optimizer:
      epochs: 1
      batch: 128
      name: Adam
      split: .8
      lr: .01
  trajectory_based_prob:
    training:
      hid_width: 250
      hid_depth: 2
      E: 5
    optimizer:
      epochs: 1
      batch: 128
      name: Adam
      split: .8
      lr: .003
  one_step_det:
    training:
      hid_width: 250
      hid_depth: 2
      E: 5
    optimizer:
      epochs: 1
      batch: 128
      name: Adam
      split: .8
      lr: .003
  one_step_prob:
    training:
      hid_width: 250
      hid_depth: 2
      E: 5
    optimizer:
      epochs: 1
      batch: 128
      name: Adam
      split: .8
      lr: .003
