collect_data: true
train_traj_based: true
train_det: true
train_prob: false



experiment:
  traj_len: 600
  traj_len_test: 800
  num_traj: 10
  split: .8
  P: false
  D: false

experiment_efficiency:
  traj_len: 30
  traj_len_test: 200
  num_traj: 10

nn:
  trajectory_based:
    ensemble:
      use: false
      num_nets: 10
    training:
      hid_width: 250
      hid_depth: 2
      E: 5
    optimizer:
      epochs: 1
      batch: 128
      name: Adam
      split: .8
      lr: .003
  one_step_det:
    ensemble:
      use: false
      num_nets: 10
    training:
      hid_width: 250
      hid_depth: 2
      E: 5
    optimizer:
      epochs: 1
      batch: 128
      name: Adam
      split: .8
      lr: .003
  one_step_prob:
    ensemble:
      use: false
      num_nets: 10
    training:
      hid_width: 250
      hid_depth: 2
      E: 5
    optimizer:
      epochs: 1
      batch: 128
      name: Adam
      split: .8
      lr: .003
