collect_data: true
create_dataset: true
train_model: true
train_model_onestep: true

experiment:
  traj_len: 600
  traj_len_test: 800
  num_traj: 50
  split: .8
  P: false
  D: false

nn:
  ensemble: false
  training:
    hid_width: 250
    hid_depth: 2
    E: 5
    plot_loss: true
    plot_loss_epoch: true
  optimizer:
    epochs: 3
    batch: 128
    name: Adam
    split: .8
    lr: .025
