defaults:
  - models: t
  - envs: reacher

mode: collect # train or collect
data_dir: l500_t100_v1.dat
model_dir: l500_t50_v5.dat
exper_dir: false # set to a name to save models within a subfolder in the models directory
plot: false
video: true
PID_test: true
#determines whether target is part of input data
train_target: false
control_params: true

hydra:
  run:
    dir: ./outputs/${now:%Y-%m-%d}/${now:%H-%M-%S}
  sweep:
    dir: ./outputs/${now:%Y-%m-%d}/${now:%H-%M-%S}
    subdir: ${hydra.job.num}
  job:
    config:
      override_dirname:
        kv_sep: '='
        item_sep: ','
        exclude_keys: ['random_seed']

training:
  num_traj: 20
  t_range: 500
