defaults:
  - models: t
  - envs: reacher

mode: train # train or collect
data_dir: l500_t50_v5.dat
model_dir: l500_t50_v5.dat
exper_dir: false # set to a name to save models within a subfolder in the models directory
plot: false

hydra:
  run:
    dir: ./outputs/${now:%Y-%m-%d}/${now:%H-%M-%S}
  sweep:
    dir: ./outputs/${now:%Y-%m-%d}/${now:%H-%M-%S}
    subdir: ${hydra.job.num}
  job:
    config:
      override_dirname:
        kv_sep: '='
        item_sep: ','
        exclude_keys: ['random_seed']

plotting:
  models: []
  states: true
  mse: true

experiment:
  traj_len: 500
  traj_len_test: 500
  num_traj: 50
  num_traj_test: 5
  split: .8
  P: false
  D: false

experiment_efficiency:
  traj_len: 30
  traj_len_test: 200
  num_traj: 10
