model:
  str: t_7
  prob: false
  ensemble: false
  traj: true
  delta: false
  training:
    hid_width: 250
    hid_depth: 2
    E: 1
    # Note: these do nothing for non trajectory based models
    train_target: true
    control_params: true
    # the state indices to worry about for model
    state_indices: [0,1,2,3,4,5,6,7,8,9,13,14,15,16,17]
    filter_rate: 0.7
  optimizer:
    epochs: 20
    batch: 32
    name: Adam
    split: .8
    lr: .0005
    max_size: 50000
  preprocess:
    state:
      class: sklearn.preprocessing.StandardScaler
    index:
      class: sklearn.preprocessing.MinMaxScaler
      params:
        feature_range: [-1.,1.]
    param:
      class: sklearn.preprocessing.MinMaxScaler
      params:
        feature_range: [-1.,1.]
    output:
      class: sklearn.preprocessing.StandardScaler
  plotting:
    label: Trajectory Based Deterministic, 0.7 filtering
    color: '#ebeb34'
    color_plotly: rgb(235,235,52)
    marker: s
    marker_plotly: cross-open-dot
